### ISSUE TITLE
Can this be used with home-manager

### ISSUE THREAD

**Issue by stephenandary** [nix-community/nix4vscode#12]
Is it possible to use this with home-manager vscodium config, to manage open-vsx extensions?

Are there any examples using with home-manager?

**Comment by cathaysia** [comment]
this can be used with home manager surely, but it not support openvsx at now.
________________________________
From: Stephen Andary ***@***.***>
Sent: Saturday, December 9, 2023 6:00:31 AM
To: nix-community/nix4vscode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nix-community/nix4vscode] Can this be used with home-manager (Issue #12)


Is it possible to use this with home-manager vscodium config, to manage open-vsx extensions?

Are there any examples using with home-manager?

―

**Comment by stephenandary** [comment]
Good to know, open-vsx is what I am trying to use. Thank you! Will close issue.
