### ISSUE TITLE
Provide flake?

### ISSUE THREAD

**Issue by yajo** [nix-community/nix4vscode#124]
I'm getting some problems with https://github.com/nix-community/nix-vscode-extensions and considering using this project.

However I have no experience on rust packaging nor compiling.

Would you please add a `flake.nix` (or `default.nix`) to this project and provide a nix package that we can easily consume and use?

Thanks!

**Comment by cathaysia** [comment]
you should could download pre-build binaries from https://github.com/nix-community/nix4vscode/releases

Is this suit for you?

**Comment by yajo** [comment]
I see nothing in that page.

**Comment by cathaysia** [comment]
this should be ok now. And I add flake for build this project.

close by 37006abdfb3c70dbe313037b2c387c1874b2116d
