### ISSUE TITLE
Wrong hash for jupyter extension

### ISSUE THREAD

**Issue by leon-erd** [nix-community/nix4vscode#18]
Somehow I get a wrong hash for the jupyter extension.

```toml
vscode_version  = "1.86.2"
[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter"
```

returns this:

```nix
"ms-toolsai"."jupyter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "jupyter";
    publisher = "ms-toolsai";
    version = "2024.1.2024012502";
    sha256 = "11dq86kxm3yqyykrv7xnq8nfim0jx16ni6hj75chbhsynvdjkb8x";
  };
```

When trying to build the system with this it gives me the following error. Inserting the correct hash into the nix expression manually works. For all my other extensions it works as well. Its just jupyter...

```bash
error: hash mismatch in fixed-output derivation '/nix/store/qsz7qn7ixnqf2x86x1inrwbyn8ls7rhp-ms-toolsai-jupyter.zip.drv':
         specified: sha256-Ha0p27ZewwVZORKaaE3oEtToLMK2n52n99iP2qdBuIU=
            got:    sha256-q4y8TGEzqd0J6GREvDdXnkL7/xYXOXk+TkvEaX3A40o=
error: 1 dependencies of derivation '/nix/store/rf6d3b6qpbwi8arbidb953bakwf202mq-vscode-extension-ms-toolsai-jupyter-2024.1.2024012502.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f917lzb28jnb0jy9yswkml6skdwv3cna-hm_.vscodeossextensions.extensionsimmutable.json.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r7c4k4abqcdlhdj62xkirh5bw77qkbhy-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/788vkjbr60h6k7dxbsswx3ixk6bcp8m3-home-manager-generation.drv' failed to build
```

**Comment by cathaysia** [comment]
This bug can be reproduced. nix4vscode uses nix-prefetch-url to calculate the hash of the file. However, the inconsistency between nix-prefetch-url and the hash calculated by nix causes this problem.

Consider this a bug in nix-prefetch-url. The following are related issues:

https://github.com/NixOS/nix/issues/10127

**Comment by thufschmitt** [comment]
I compared the output of `nix-prefetch-url` and the one that the Nix expression tries to fetch:

```console
$ echo $NIX_PREFETCH_URL_OUTPUT
11dq86kxm3yqyykrv7xnq8nfim0jx16ni6hj75chbhsynvdjkb8x
/nix/store/2di7lv008fv7b71zd9p2w94dq3j6lfa9-Microsoft.VisualStudio.Services.VSIXPackage
$ NIX_PREFETCH_URL_OUTPUT=$(nix-prefetch-url https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2024.1.2024012502/1706210577096/Microsoft.VisualStudio.Services.VSIXPackage --print-path | tail -n1)
$ NIX_BUILD_OUTPUT=$(nix-build --expr 'with import <nixpkgs> { }; (vscode-utils.extensionFromVscodeMarketplace {
    name = "jupyter";
    publisher = "ms-toolsai";
    version = "2024.1.2024012502";
    sha256 = "sha256-q4y8TGEzqd0J6GREvDdXnkL7/xYXOXk+TkvEaX3A40o=";
  }).src')
$ diffoscope $NIX_PREFETCH_URL_OUTPUT $NIX_BUILD_OUTPUT 
...
```

The diffoscope result shows that the file are fairly different. The interesting bit, I guess is:

```diff
-    <Identity Language="en-US" Id="jupyter" Version="2024.1.2024012502" Publisher="ms-toolsai" TargetPlatform="alpine-x64"/>
+    <Identity Language="en-US" Id="jupyter" Version="2024.1.2024012502" Publisher="ms-toolsai" TargetPlatform="alpine-arm64"/>
```

(notice the different `TargetPlatform`).

If I force the arch in the call to `extensionFromVscodeMarketplace` (by passing `arch="alpine-x64"`), I get the same path for `nix-prefetch-url` and `nix-build`

**Comment by cathaysia** [comment]
Confirmed to be a problem with nix4vscode. it does not handle target_platform

**Comment by cathaysia** [comment]
I add a patch fix this: https://github.com/nix-community/nix4vscode/pull/21 . Is it suitable for you?

**Comment by leon-erd** [comment]
Yes it fixes the hash problem! :)
However, I noticed two other things (problems). 
FIrst: I get a bunch of warning (see below). They are printed out on stdout and not stderr so `nix4vscode extensions.toml > file.nix` won't work.

![swappy-20240304_012749](https://github.com/nix-community/nix4vscode/assets/99900077/4b0a8b5b-dfc8-495d-accb-15f139f996bf)

Second: lib.attrsets.optionalAttrs seems to override (delete) all other extensions from the same publisher when evaluated.
Having 
```toml
[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter"

[[extensions]]
publisher_name = "ms-toolsai"
extension_name = "jupyter-keymap"
```
and then building with the generated extensions.nix file will raise `error: attribute 'jupyter-keymap' missing`

**Comment by cathaysia** [comment]
I add two commit fix these questions, now the log will always print to stderr, and ensure previous attr not be overrited.

note that nix4vscode have a option `-o` used write result to file but not stdoput. :)

**Comment by leon-erd** [comment]
Ah I didn't know about the `-o` option maybe should add this to the README.
And yeah the fixes work!
However, the new branch seems to pull outdated versions for some extensions (see below) compared to the main branch.

![swappy-20240304_151601](https://github.com/nix-community/nix4vscode/assets/99900077/829d303d-ce3f-49e5-b959-a0aca6350a8a)

**Comment by leon-erd** [comment]
Sure sure! Should I open a new issue for the outdated versions? :)

**Comment by cathaysia** [comment]
No, I will fix these bugs together before integrating them into the main line so as not to disrupt other people's existing workflows.
________________________________

**Comment by cathaysia** [comment]
i push some commits today, does it fix these bugs? I test it locally, but I am afraid not cover corner case.
________________________________

**Comment by leon-erd** [comment]
I think it works as you want. It pulls the same versions as the main branch and the other bugs also seem fixed.
However, I once again discovered something odd :sweat_smile:. 
I think for some extensions it pulls versions that are too new. But this is already the case in the main branch so nothing introduced by these commits.
An example is once again jupyter. With `vscode_version  = "1.86.2"` in `config.toml` it generates jupyter with version `2024.1.2024012502`. This version does not work with my vscodium. If I install the extension manually in vscodium it installs version `2023.9.100` which works. So I assume this is the latest compatible version with vscode 1.86.2 which should also be generated by this repo.

**Comment by cathaysia** [comment]
as a interesting result, the engine compatible in the [package.json](https://github.com/microsoft/vscode-jupyter/blob/df113e13a83a665f701fb62aa2cde342c031ca70/package.json#L32) of jupyter 202401 is `^1.86.0`, so it should work with 1.86.2. Is your vscodium really 1.86.2, or you should use openvsx instead?

**Comment by leon-erd** [comment]
Yes it is `1.86.2` :sweat_smile:. Maybe its something with my setup even though I don't think this is the case bc vscodium itself installs a lower version.

**Comment by cathaysia** [comment]
is your system linux or macos? On macos, when you upgrade your flake, you need recreate icon in the dock. The best way is check the code's version by codes' reference, but not flake.

**Comment by leon-erd** [comment]
Running linux

```bash
➜  ~ disfetch
       \\    \\  //      WE| leon @ leon-inspiron
        \\    \\//       RD| OS:        nixos 24.05 (uakari)
    ::::://====\\  //    GN| KERNEL:    6.7.6
       ///      \\//     YW| ARCH:      x86_64
  """"//\\      ///""""  BE| UPTIME:    4 hours 23 minutes
     //  \\====//:::::   MA| PACKAGES:  2634
        //\\    \\       CN| SHELL:     zsh
       //  \\    \\      BK| DESKTOP:   hyprland
```

**Comment by cathaysia** [comment]
the reason is vscodium using openvsx but not vscode marketplace, but openvsx is outdated. If you [Making vscoduim using vscode marketplace](https://www.[flypenguin.de/2023/02/26/use-vscodium-with-microsofts-proprietary-marketplace/](https://www.flypenguin.de/2023/02/26/use-vscodium-with-microsofts-proprietary-marketplace/)), you can using latest extension:

![image](https://github.com/nix-community/nix4vscode/assets/42114817/6e933d69-c6d9-481c-9154-9ab0f112cc61)
![image](https://github.com/nix-community/nix4vscode/assets/42114817/1409f5eb-17a0-48a9-b5a8-ceb4f0fd66bb)

if does not:
![image](https://github.com/nix-community/nix4vscode/assets/42114817/f1c2cea9-a406-4d59-9ef4-20961b4a26bf)
![image](https://github.com/nix-community/nix4vscode/assets/42114817/356e501b-6263-429e-ab64-803fa3ecde53)

**Comment by cathaysia** [comment]
nix4vscode doesn't support openvsx for now, If you use vscodium, I recommend you use vscode marketplace

**Comment by cathaysia** [comment]
I plan to merge PR into the branch first. If you have other questions, please be free open a new issue.
