### ISSUE TITLE
cargo run -- -f config.toml not working

### ISSUE THREAD

**Issue by fillon** [nix-community/nix4vscode#4]
Hi

Trying to generate the nix expression.

`cargo run -- -f config.toml`

I have this error

```txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/nix4vscode -f config.toml`
error: unexpected argument '-f' found

  tip: to pass '-f' as a value, use '-- -f'

Usage: nix4vscode [OPTIONS] <FILE>

For more information, try '--help'.
```

I am a rust virgin ^_^ i might be doing something wrong

**Comment by fillon** [comment]
I got it working by removing `-f` in the command.

**Comment by cathaysia** [comment]
yes, I updated the README, I last updated the command line parameters and removed the -f parameter to make the cli more concise.

use `cargo run -- config.toml` now.
