### ISSUE TITLE
Cannot get engine version

### ISSUE THREAD

**Issue by BapRx** [nix-community/nix4vscode#7]
I think there is a regression between the 2 commits [05838ef..5c9feb2](https://github.com/nix-community/nix4vscode/compare/05838ef..5c9feb2)

I couldn't test the intermediate commits due to rust crashing but with the 1st commit, 93/95 extensions from my config were converted to nix but with the 2nd commit only 9/95 succeeded.

I get warning message for different versions of every failing extention, eg: `src/main.rs:58: Cannot get engine version for GitLab.gitlab-workflow 2.2.0`

**Comment by cathaysia** [comment]
Yes, I encountered this problem too. According to the current logs, it is because the requested data is missing some data. I will fix it as soon as possible.

**Comment by cathaysia** [comment]
I recently committed some changes, is there any improvement in your scenario?

**Comment by BapRx** [comment]
I just tried 1f1537c but I get the same result, here's my config.toml: [config.txt](https://github.com/nix-community/nix4vscode/files/13426667/config.txt) (I had to change the extension to upload on GH)

**Comment by cathaysia** [comment]
ok, thanks

**Comment by cathaysia** [comment]
dev branch should fix this. can you give it a try?

**Comment by BapRx** [comment]
The issue is fixed on `dev` branch thanks!

**Comment by cathaysia** [comment]
thanks for your report. :)
